name: tensorflow
dependencies:
    - python=3.8.12
    - pip
    - jupyter
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - pillow
    - tqdm
    - requests
    - h5py
    - pyyaml
    - flask
    - boto3
    - lxml
    - nltk
    - black
    - numpy
    - pydot
    - keras
    - plotly
    - pylint
    - seaborn
    - openpyxl
    - html5lib
    - sqlalchemy
    - cufflinks-py
    - BeautifulSoup4
    - tensorboard
    - apple::tensorflow-deps
    - pip:
        - tensorflow-macos
        - tensorflow-metal
        - bayesian-optimization
        - gym
        - kaggle